# Generated by Django 5.2.4 on 2025-08-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Performance',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
